# -------------------------
# Phil McMinn's .zshrc file
# -------------------------

# Language
export LANG=en_GB.UTF-8

# Local paths
export P_REPOS="$HOME/repos"
export P_MF="$P_REPOS/machine-files"
export P_GL="$P_MF/log/git"

# Load custom shell commands
custom_shell_command_dirs=(bin bin/git bin/latex)
for dir in $custom_shell_command_dirs; do
  abs_path="$P_MF/$dir"
  export PATH="$PATH:$abs_path"
  source "$abs_path/commands"
done

# Load key files
source "$P_MF/keys/keys"

# Set editor
export EDITOR=nvim

# What OS is this?
export P_MAC=false
export P_LINUX=false
case "$(uname -s)" in
  Darwin)
    export P_MAC=true
    ;;
  Linux)
    export P_LINUX=true
    ;;
esac

# Set host environment variable
if [[ $P_MAC == true ]]; then
  export P_HOST=$(scutil --get LocalHostName)
elif [[ $P_LINUX == true ]]; then
  export P_HOST=$(hostname)
fi

# Mac OS specific ...
if [[ ${P_MAC} == true ]]; then
  # Add Brew to PATH
  export PATH="/opt/homebrew/bin:${PATH}"

  # Load asdf for managing different command versions (e.g. Ruby)
  . "$(brew --prefix asdf)/libexec/asdf.sh"

  # Enable vi mode in the terminal
  source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
fi

# Start Starship
eval "$(starship init zsh)"

